CREATE TABLE IF NOT EXISTS Genre(
	Genre_id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Singer(
	Singer_id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre_Singer(
	Genre_id INTEGER REFERENCES Genre ON DELETE SET NULL,
	Singer_id INTEGER REFERENCES Singer ON DELETE SET NULL,
	PRIMARY KEY (Genre_id, Singer_id)
);

CREATE TABLE IF NOT EXISTS Albom(
	Albom_id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	year_release INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Singer_Albom(
	Singer_id INTEGER REFERENCES Singer ON DELETE SET NULL,
	Albom_id INTEGER REFERENCES Albom ON DELETE SET NULL,
	PRIMARY KEY (Singer_id, Albom_id)
);

CREATE TABLE IF NOT EXISTS Track(
	Track_id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	duration numeric(4,2) NOT null,
	Albom_id INTEGER REFERENCES Albom ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Collection(
	Collection_id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	year_release INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Collection_Track(
	Collection_id INTEGER REFERENCES Collection ON DELETE SET NULL,
	Track_id INTEGER REFERENCES Track ON DELETE SET NULL,
	PRIMARY KEY (Collection_id, Track_id)
);